### ISSUE TITLE
Where do you use the Widget-options.vue Component ?

### ISSUE THREAD

**Issue by Nayir** [jappi00/Maps-Widget#1]
I can't find where the script `widget-options.js` , from the component `widget-options.vue` is used. Can you help me ? 

Thanks for this extension, and thanks for the answer

**Comment by jappi00** [comment]
Jeah, maybe that is an old Version on GitHub. I'm not at home. I help you tomorrow.

**Comment by jappi00** [comment]
But i think that is an old file

**Comment by jappi00** [comment]
So, the file was an Test for multiple maps on one page,
but I have problems with that. In an future update when I understand how i can do this the file will used...
Sorry for my bad English...
