### ISSUE TITLE
Can't enable maps during or after installing

### ISSUE THREAD

**Issue by humantex** [jappi00/Maps-Widget#5]
I get an error if I try to enable it from the marketplace's modal popup, or from the list of installed extensions. The screengrab shows the error - and it's the same for either method.

![pagekit-maps-error](https://user-images.githubusercontent.com/16087649/28945004-bda105a4-7872-11e7-9dbb-47ae2e0acbad.png)

[edit to add]
Should have mentioned a few things too...
Windows 7 dev machine w/
- Pagekit version: 1.0.12
- Webserver: Ampps 3.7 [Apache 2.4.25]
- Database:  sqlite 3.8.10.2
- PHP Version: 5.6.30

**Comment by jappi00** [comment]
I will fix it in a minute
